# Generated by Django 5.1.1 on 2025-06-11 12:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('education_level', models.CharField(choices=[('high_school', 'High School'), ('diploma', 'Diploma/Certificate'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=20)),
                ('current_occupation', models.CharField(max_length=100)),
                ('annual_income', models.CharField(blank=True, max_length=50)),
                ('trading_experience', models.CharField(choices=[('beginner', 'Complete Beginner (0-6 months)'), ('novice', 'Novice (6 months - 2 years)'), ('intermediate', 'Intermediate (2-5 years)'), ('advanced', 'Advanced (5+ years)')], max_length=20)),
                ('previous_trading_education', models.TextField(blank=True, help_text="Describe any previous trading courses, books, or education you've had")),
                ('trading_goals', models.TextField(help_text='What do you hope to achieve through this program?')),
                ('desired_course', models.CharField(choices=[('basic', 'Basic Forex Fundamentals ($1,997)'), ('premium', 'Premium Trading Mastery ($2,997)'), ('vip', 'VIP Mentorship Program ($4,997)')], max_length=20)),
                ('payment_plan', models.CharField(choices=[('full', 'Full Payment (5% discount)'), ('installments_3', '3 Monthly Installments'), ('installments_6', '6 Monthly Installments')], max_length=20)),
                ('study_time_per_week', models.IntegerField(help_text='How many hours per week can you dedicate to studying?')),
                ('start_date_preference', models.DateField(help_text='When would you like to start the program?')),
                ('motivation', models.TextField(help_text='Why do you want to learn forex trading? What motivates you?')),
                ('financial_goals', models.TextField(help_text='What are your short-term and long-term financial goals?')),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative - I prefer steady, lower returns'), ('moderate', 'Moderate - I accept some risk for better returns'), ('aggressive', "Aggressive - I'm willing to take high risks for high returns")], max_length=50)),
                ('how_did_you_hear', models.CharField(help_text='How did you hear about TradeWise Academy?', max_length=100)),
                ('additional_comments', models.TextField(blank=True, help_text="Any additional information you'd like us to know?")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
