# Generated by Django 5.1.1 on 2025-06-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='payment_plan',
        ),
        migrations.AlterField(
            model_name='application',
            name='desired_course',
            field=models.CharField(choices=[('basic', 'Basic Forex Fundamentals'), ('premium', 'Premium Trading Mastery '), ('vip', 'VIP Mentorship Program )')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='how_did_you_hear',
            field=models.CharField(help_text='How did you hear about Themosempire Fx?', max_length=100),
        ),
    ]
